### PR TITLE
Task5. Add AWS S3 import service

### PR DESCRIPTION
**Pull request by maryna-karpovets**
Task [https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task5-import-to-s3/task.md](https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task5-import-to-s3/task.md)

All required and additional tasks were done:
1 - File serverless.yml contains configuration for `importProductsFile` function
3 - The `importProductsFile` lambda function returns a correct response which can be used to upload a file into the S3 bucket
4 - Frontend application is integrated with `importProductsFile` lambda
5 - The `importFileParser` lambda function is implemented and serverless.yml contains configuration for the lambda

Additional tasks:
+1 - async/await is used in lambda functions
+1 - `importProductsFile` lambda is covered by unit tests (aws-sdk-mock is used to mock S3 methods).
Also, I have covered`importFileParser` lamda by a unit test.
+1 - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into the parsed folder, and then deleted from the uploaded folder)

Front-end link: [https://d2kdkgfbzg2dbv.cloudfront.net/admin/products](https://d2kdkgfbzg2dbv.cloudfront.net/admin/products)

Score 8 / 8

### CODE REVIEW

**Review by Konstantin1996 — APPROVED** [review]

**Comment by Konstantin1996** [comment]
I got 403 trying to upload my csv file. 

image

**Comment by Konstantin1996** [comment]
Try to add this to your bucket policy in your S3 -> permissions 
image


```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::importservice-bucket/*"
        },
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::importservice-bucket/*"
        }
    ]
}
```

**Comment by maryna-karpovets** [comment]
> Try to add this to your bucket policy in your S3 -> permissions
> image
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "AllowPublicRead",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "*"
>             },
>             "Action": "s3:GetObject",
>             "Resource": "arn:aws:s3:::importservice-bucket/*"
>         },
>         {
>             "Sid": "AllowPublicRead",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "*"
>             },
>             "Action": "s3:PutObject",
>             "Resource": "arn:aws:s3:::importservice-bucket/*"
>         }
>     ]
> }
> ```



It is weird because I do not have any errors locally or remotely. But I did not have `"Action": "s3:PutObject"`. I added it. I guess it can help. Anyway, it is strange that I do not have errors.


Here are screenshots:



Screenshot 2020-11-16 at 19 12 38

Screenshot 2020-11-16 at 19 16 00

**Comment by Konstantin1996** [comment]
It does not help. Yes, it is strange, I'll change mark to 8.

**Comment by maryna-karpovets** [comment]
> It does not help. Yes, it is strange, I'll change mark to 8.

 I added one more action to IAM rules, delete object. Anyway, it worked before/now and I sent you screenshots. I can't fix what I do not have.

**Pull request merged**
